### ISSUE TITLE
It Froze and gave me an Undefined action on level 4

### ISSUE THREAD

**Issue by CaKellum** [XavierMB289/XavierMB289.github.io#2]
## Error on console 

Happened Twice

```
Uncaught TypeError: can't access property 4, level.level[prevItemIndex] is undefined
    batteryUpdate https://xaviermb289.github.io/logicGateGame/js/gates.js:17
    loadGameLevel https://xaviermb289.github.io/logicGateGame/js/game.js:54
    onreadystatechange https://xaviermb289.github.io/logicGateGame/js/functions.js:12
gates.js:17:5
    batteryUpdate https://xaviermb289.github.io/logicGateGame/js/gates.js:17
    loadGameLevel https://xaviermb289.github.io/logicGateGame/js/game.js:54
    onreadystatechange https://xaviermb289.github.io/logicGateGame/js/functions.js:12
```
## Image Associated with error

![ Game error screenshot](https://user-images.githubusercontent.com/42648546/129206451-9210d63b-cac9-4707-983f-6d17c0390466.png)

**Comment by XavierMB289** [comment]
This should be fixed with the most recent update. Thank you for bringing this to my attention. Current issue with how updates roll out is a personal one (keep forgetting to change off of the master branch when pushing experimental builds). Thank you again for your patience.
